name: Deploy

on: 
  push:
    branches:
      - backend
      - master
#     path-ignore:
      # - ' .github/workflows/*'
# env:
  # name: goupriveq
  # gh-secrets: ${{secrets.SSH-KEY}}
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
#       - name: string
        # run: | 
          # echo "${{ env.name }}"
    - name: copy repo
      uses: actions/checkout@v3
    - name: i deps
      run: npm ci

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: copy repository contents in VPS
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/root"
#         target: "/var/www/mywebsite"
    - name: executing remote command
      uses: appleboy/ssh-action@master
      env:
        APP_ID: ${{ secrets.APP_ID }}
        API_KEY: ${{ secrets.API_KEY }}
        AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
        MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        envs: APP_ID, API_KEY, AUTH_DOMAIN, MESSAGING_SENDER_ID, PROJECT_ID, STORAGE_BUCKET
        script: |
          mkdir firstDir
          npm ci
          npm start
