name: Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/var/www/mywebsite"

    - name: Executing remote command
      uses: appleboy/ssh-action@master
      env:
        REACT_APP_API_KEY: ${{ secrets.API_KEY }}
        REACT_APP_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
        REACT_APP_PROJECT_ID: ${{ secrets.PROJECT_ID }}
        REACT_APP_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
        REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
        REACT_APP_APP_ID: ${{ secrets.APP_ID }}
      with:
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        script: mkdir myNewFolder; echo $(env.REACT_APP_API_KEY) >> lol