name: Deploy

on: [push]

env:
  MY_ENV_VAR: ${{ secrets.HOST }}
  DAY_OF_WEEK: Monday

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Copy repository contents via scp
      uses: appleboy/scp-action@master
      env:
        HOST: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
      with:
        source: "."
        target: "/var/www/mywebsite"
    - name: Executing remote command
      uses: appleboy/ssh-action@master
      env:
          REACT_APP_API_KEY: ${{ secrets.API_KEY }}
      with:
        # REACT_APP_API_KEY: ${{ secrets.API_KEY }}
        # REACT_APP_AUTH_DOMAIN: ${{ secrets.AUTH_DOMAIN }}
        # REACT_APP_PROJECT_ID: ${{ secrets.PROJECT_ID }}
        # REACT_APP_STORAGE_BUCKET: ${{ secrets.STORAGE_BUCKET }}
        # REACT_APP_MESSAGING_SENDER_ID: ${{ secrets.MESSAGING_SENDER_ID }}
        # REACT_APP_APP_ID: ${{ secrets.APP_ID }}
        host: ${{ secrets.HOST }}
        USERNAME: ${{ secrets.USERNAME }}
        PORT: ${{ secrets.PORT }}
        KEY: ${{ secrets.SSHKEY }}
        # echo "$Greeting $First_Name. Today is $DAY_OF_WEEK!"
        # run: |
          # cat $MY_ENV_VAR > a.q
          # mkdir a
        # script: echo "$MY_ENV_VAR" > env
      - script: |
        echo "$MY_ENV_VAR" > env
        echo "$DAY_OF_WEEK" > week
    # - run: npm i
    # - run: npm run build --if-present